# TOKEN_MAP = {
#   "axes": ["<axes>", "</axes>"],
#   "chart_type": ["<chart_type>", "</chart_type>"],
#   "bars": ["<bars>", "</bars>"],
#   "data_series": ["<data_series>", "</data_series>"],
#   "plot_bb": ["<plot_bb>", "</plot_bb>"],
#   "source": ["<source>", "</source>"],
#   "text": ["<text>", "</text>"],
#   "text_display": ["<text_display>", "</text_display>"],
#   "x_axis": ["<x_axis>", "</x_axis>"],
#   "y_axis": ["<y_axis>", "</y_axis>"],
#   "x": ["<x>", "</x>"],
#   "y": ["<y>", "</y>"],
#   "x0": ["<x0>", "</x0>"],
#   "x2": ["<x2>", "</x2>"],
#   "y0": ["<y0>", "</y0>"],
#   "y2": ["<y2>", "</y2>"],
#   "id": ["<id>", "</id>"],
#   "polygon": ["<polygon>", "</polygon>"],
#   "role": ["<role>", "</role>"],
#   "bos_token" : ["</s>"]
# }
TOKEN_MAP = {'text': ['<text>', '</text>'],
 'text_display': ['<text_display>', '</text_display>'],
 'role': ['<role>', '</role>'],
 'data_series': ['<data_series>', '</data_series>'],
 'y': ['<y>', '</y>'],
 'chart_type': ['<chart_type>', '</chart_type>'],
 'y0': ['<y0>', '</y0>'],
 'x': ['<x>', '</x>'],
 'polygon': ['<polygon>', '</polygon>'],
 'plot_bb': ['<plot_bb>', '</plot_bb>'],
 'x2': ['<x2>', '</x2>'],
 'color': ['<color>', '</color>'],
 'x0': ['<x0>', '</x0>'],
 'y2': ['<y2>', '</y2>'],
 'colors': ['<colors>', '</colors>'],
 'bos_token': ['</s>']}