general:
  fast_dev_run: True
  seed: 137




model:
  backbone_path: google/matcha-base
  max_length: 512
  max_patches: 1024
  patch_size: 16
  len_tokenizer: ???
  pad_token_id: ???
  decoder_start_token_id: ???
  bos_token_id: ???
  max_length_generation: 512


train_params:
  train_bs: 2
  valid_bs: 2
  num_epochs: 10
  grad_accumulation: 16
  use_fp16: true
  num_workers: 4
  swa_epoch_start: 0.7
  swa_lrs: 5e-5
  swa_annealing_epochs: 3
  swa_annealing_strategy: cos
  estimated_steps_per_epoch: 100


optimizer:
  lr: 0.01
  weight_decay: 0.001
  grad_clip_value: 1.0



learning_rate_scheduler:
  warmup_pct: 0.3
  


metrics_tolerance:
  numeric_tolerance: 0.05
  string_tolerance: 2

outputs:
  model_dir: /kaggle/working/model_dir

best_ckpt:
  monitor: 'val_f1'
  mode: 'max'
  save_top_k: 2

early_stopping:
  monitor: 'val_f1'
  patience: 2
  mode: 'max'



dataset:
  parquet_dict: /kaggle/working/ChartQa_clean/data
  percent_to_take_in_train: 0.006711409396



wandb:
  project: mga-dev-a1
  run_name: rb-exp100-r-final


images:
  rsz_height: 512
  rsz_width: 512



